### ISSUE TITLE
As a prospective client or partner, I should see case studies for major projects, so I can understand Bivee's process and approach to solving problems

### ISSUE THREAD

**Issue by jayperryworks** [biveeco/biveeco.github.io#1]
## Considerations
- Case studies should show results, but should focus quite a bit on process: how we collaborated with the client and understood their needs, how we framed and approached problems, and how we scaled/built capacity, etc.
- Because we don't have tons of spare time to individually design or write these, the layout should be as simple and modular as possible.
- They should be visually interesting and easy to skim, preferably with short passages or text interspersed with graphics.

## Tasks
- [x] write content and choose projects
    - [x] PPP
    - [x] DDH
    - [x] Sendai
- [x] wireframes
- [x] stub out html
- [x] set up layout styles
- [x] set up UI components/partials
- [ ] set up templates and real content
- [ ] set up photos for headers
