### ISSUE TITLE
As a user, I should be able to read blog posts from Bivee staff, so that I can more deeply engage with Bivee's wide expertise and approach to solving problems.

### ISSUE THREAD

**Issue by jayperryworks** [biveeco/biveeco.github.io#2]
## Considerations
- We should work out a realistic but regular editorial calendar, to ensure new posts arrive on the blog with reasonable frequency.
- We should also figure out some good style & tone guidelines, so the 'voice' is to some degree consistent regardless of author.
- Blog posts can be writing, of course, but they might also consist of photos, videos, slide decks, or recorded presentations. The layout should be flexible enough to work with various kinds of media and content.
- We should consider how to integrate the blog with personal websites and re-posted content, so staff can easily add content from their other channels if it's appropriate to Bivee's site. Might be a way to handle this with RSS feeds or common metadata?

## Tasks
- [ ] Compile a few "seed" posts to design around, possibly from previous presentations or articles we've written
- [ ] Figure out editorial calendar
- [ ] Write some basic style guidelines (length, tone, usage, etc.)
- [ ] Wireframes
- [ ] Stub out markup and templates
- [ ] Set up UI components
